"""Write css/skins.css and the skin table for js/skins.js from the verified data.

Generated rather than typed. Twenty four skins times twelve colours is nearly
three hundred hex values, and the point of checking them in one place is lost
if they are then copied by hand into another.
"""

import io
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = "C:/Users/zpsja/recall"

data = json.load(io.open(os.path.join(HERE, "skins.json"), encoding="utf-8"))
P, FONTS, LAYOUTS, SKINS = data["palettes"], data["fonts"], data["layouts"], data["skins"]

# Which faces are not already on the phone. The files themselves live in
# fonts/ and are declared in css/fonts.css, so this only records that the skin
# wants type the device does not have, which the picker uses for nothing and
# the tests use to prove the four no-download skins really need none.
GF = {
  "atkinson": "Atkinson+Hyperlegible:wght@400;700",
  "lexend": "Lexend:wght@400;600;700",
  "public": "Public+Sans:wght@400;600;700",
  "literata": "Literata:opsz,wght@7..72,400;7..72,700",
  "nunito": "Nunito:wght@400;700",
  "archivo": "Archivo:wght@400;700;800",
  "oswald": "Oswald:wght@400;600;700",
  "mono": "Roboto+Mono:wght@400;700",
  "bitter": "Bitter:wght@400;700",
}

# ------------------------------------------------------------------- the css
def _chan(v):
    c = v / 255.0
    return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4


def paper_is_dark(hexv):
    """Whether a palette is a night one, which decides the chrome band."""
    h = hexv.lstrip("#")
    r, g, b = (_chan(int(h[i:i + 2], 16)) for i in (0, 2, 4))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b < 0.4


out = []
out.append("""/* Recall skins. GENERATED by tools/gen_skins.py from the verified
   palette table: do not edit by hand, edit the table and run it again.

   A skin is four things, and all four are tokens so the stylesheet never has
   to know which one is on:

     colour   the eleven colour tokens style.css already uses
     --face   the type stack
     --radius corner rounding
     --edge   border weight
     --base   the root font size, never below 22px

   Every ratio here was checked by role before it was written: 4.5:1 for text,
   3:1 for the button label, which is 24px at weight 700 and therefore large
   text. The layout each skin wants lives in js/skins.js, because it is a
   class on the list rather than a colour. */
""")

for s in SKINS:
    t = P[s["pal"]]
    f = FONTS[s["font"]]
    sel = ":root" if s["key"] == "warm-paper" else ':root[data-skin="%s"]' % s["key"]
    out.append("/* %s - %s layout, %s */" % (s["name"], LAYOUTS[s["layout"]]["name"], f["name"]))
    out.append("%s {" % sel)
    out.append("  --paper: %s;" % t["paper"])
    out.append("  --card: %s;" % t["card"])
    out.append("  --ink: %s;" % t["ink"])
    out.append("  --body: %s;" % t["body"])
    out.append("  --mid: %s;" % t["mid"])
    out.append("  --rule: %s;" % t["rule"])
    out.append("  --orange: %s;" % t["orange"])
    out.append("  --orange-dark: %s;" % t["orangeDark"])
    out.append("  --orange-soft: %s;" % t["orangeSoft"])
    out.append("  --on-soft: %s;" % t["onSoft"])
    out.append("  --ok: %s;" % t["ok"])
    out.append("  --on-accent: %s;" % t["onAccent"])
    # The chrome band. It used to be painted with --ink and --paper
    # directly, but ink is the TEXT colour, so on the eleven dark
    # palettes that made a bright white header sit on top of a dark
    # app, which is the opposite of what a night skin is for. These
    # two always resolve to a dark surface with light type on it.
    dark = paper_is_dark(t["paper"])
    out.append("  --bar: %s;" % (t["card"] if dark else t["ink"]))
    out.append("  --on-bar: %s;" % (t["ink"] if dark else t["paper"]))
    out.append("  --face: %s;" % f["stack"])
    out.append("  --radius: %dpx;" % s["radius"])
    out.append("  --edge: %dpx;" % s["edge"])
    out.append("  --base: %dpx;" % s["base"])
    out.append("}")
    out.append("")

# ---------------------------------------------------------------- the layouts
out.append("""/* ------------------------------------------------------------ the layouts

   Every layout is a treatment of one stable piece of markup. The row always
   carries the same buttons with the same data hooks, and always emits the
   time, the title, the rest of the line and the state, so a layout only ever
   decides what to show and where to put it. Nothing here hides a reminder,
   with one stated exception below. */

/* Cards. The default, and what the app has always done. */
:root[data-layout="cards"] .list .when { display: none; }

/* Plain list. No cards and no thumbnails: rules and text. */
:root[data-layout="plain"] .list .today-item,
:root[data-layout="plain"] .list .card {
  background: none;
  border: 0;
  border-bottom: var(--edge) solid var(--rule);
  border-radius: 0;
  box-shadow: none;
}
:root[data-layout="plain"] .list .thumb { display: none; }
:root[data-layout="plain"] .list .when { display: none; }
:root[data-layout="plain"] .list .status {
  color: var(--on-soft);
  font-weight: 700;
  background: none;
  border: 0;
  padding: 0;
}

/* Stripe. A bar down the left carries the state instead of a chip. */
:root[data-layout="stripe"] .list .today-item,
:root[data-layout="stripe"] .list .card {
  background: none;
  border: 0;
  border-left: 8px solid var(--ok);
  border-radius: 0;
  box-shadow: none;
  padding-left: 12px;
}
:root[data-layout="stripe"] .list .today-item.missed,
:root[data-layout="stripe"] .list .card.due { border-left-color: var(--orange); }
:root[data-layout="stripe"] .list .thumb { display: none; }
:root[data-layout="stripe"] .list .when { display: none; }

/* Ticket. Dashed edges and the time out in front, like an appointment slip. */
:root[data-layout="ticket"] .list .today-item,
:root[data-layout="ticket"] .list .card {
  background: none;
  border: 0;
  border-top: 2px dashed var(--rule);
  border-bottom: 2px dashed var(--rule);
  border-radius: 0;
  box-shadow: none;
}
:root[data-layout="ticket"] .list .thumb { display: none; }
:root[data-layout="ticket"] .list .when {
  display: block;
  font-size: 1.4em;
  font-weight: 700;
  color: var(--ink);
  font-variant-numeric: tabular-nums;
  letter-spacing: -.01em;
}
:root[data-layout="ticket"] .list .meta { text-transform: uppercase; letter-spacing: .06em; }

/* Time gutter. The time in a column of its own, so the shape of the day
   reads before any word does. */
:root[data-layout="gutter"] .list .today-main,
:root[data-layout="gutter"] .list .card > .card-main {
  display: grid;
  grid-template-columns: 4.6em minmax(0, 1fr);
  gap: 14px;
  align-items: start;
}
:root[data-layout="gutter"] .list .thumb { display: none; }
:root[data-layout="gutter"] .list .when {
  display: block;
  grid-row: 1;
  text-align: right;
  font-weight: 700;
  font-size: 1.15em;
  color: var(--ink);
  font-variant-numeric: tabular-nums;
  border-right: 3px solid var(--ok);
  padding-right: 12px;
  min-height: 1.4em;
}
:root[data-layout="gutter"] .list .today-item.missed .when,
:root[data-layout="gutter"] .list .card.due .when { border-right-color: var(--orange); }

/* Notice. A shouted label above the entry, impossible to skim past. */
:root[data-layout="notice"] .list .thumb { display: none; }
:root[data-layout="notice"] .list .when { display: none; }
:root[data-layout="notice"] .list .status {
  display: inline-block;
  background: var(--orange);
  color: var(--on-accent);
  font-weight: 800;
  font-size: .8em;
  letter-spacing: .14em;
  text-transform: uppercase;
  padding: 3px 10px;
  border-radius: calc(var(--radius) * .4);
  margin-bottom: 4px;
  order: -1;
}
:root[data-layout="notice"] .list .today-main > span:last-child,
:root[data-layout="notice"] .list .card-body { display: flex; flex-direction: column; }
:root[data-layout="notice"] .list .title { font-size: 1.2em; line-height: 1.15; }

/* Tiles. Two big squares. The meta goes, because a tile is a glance. */
:root[data-layout="tiles"] .list {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 12px;
  align-items: stretch;
}
:root[data-layout="tiles"] .list .today-item,
:root[data-layout="tiles"] .list .card { display: flex; flex-direction: column; }
:root[data-layout="tiles"] .list .today-main,
:root[data-layout="tiles"] .list .card > .card-main {
  flex-direction: column;
  align-items: center;
  text-align: center;
  gap: 6px;
}
:root[data-layout="tiles"] .list .thumb { width: 3.2em; height: 3.2em; font-size: 1.6em; }
:root[data-layout="tiles"] .list .meta,
:root[data-layout="tiles"] .list .when { display: none; }
:root[data-layout="tiles"] .list .today-acts { flex-direction: column; }
@media (max-width: 26rem) {
  :root[data-layout="tiles"] { grid-template-columns: 1fr; }
}

/* One thing. The only layout that changes what is on the screen rather than
   how it looks, so it is the only one that needs a rule about honesty: the
   rest are one press away and the button says how many there are. Nothing is
   ever silently dropped. */
:root[data-layout="one"]:not([data-open-all]) .today-item:not(:first-child),
:root[data-layout="one"]:not([data-open-all]) .card:not(:first-child) { display: none; }
:root[data-layout="one"] .list .today-item,
:root[data-layout="one"] .list .card {
  padding: 20px 14px;
  text-align: center;
  max-width: 100%;
}
:root[data-layout="one"] .list .today-main,
:root[data-layout="one"] .list .card > .card-main {
  flex-direction: column;
  align-items: center;
  gap: 8px;
}
:root[data-layout="one"] .list .title { font-size: 1.45em; line-height: 1.15; }
:root[data-layout="one"] .list .when {
  display: block;
  font-size: 1.1em;
  font-weight: 700;
  color: var(--ink);
}
:root[data-layout="one"] .list .thumb { width: 3.4em; height: 3.4em; font-size: 1.7em; }
.rest-btn { margin-top: 4px; }
:root:not([data-layout="one"]) .rest-btn { display: none; }
""")

css = "\n".join(out)
io.open(os.path.join(REPO, "css/skins.css"), "w", encoding="utf-8", newline="\n").write(css)
print("css/skins.css: %d skins, %.1f KB" % (len(SKINS), len(css) / 1024))

# ------------------------------------------------------------ the skin table
rows = []
for s in SKINS:
    f = FONTS[s["font"]]
    rows.append('  { key: "%s", layout: "%s", base: %d, group: "%s"%s }'
                % (s["key"], s["layout"], s["base"], s["group"],
                   (', face: "%s"' % s["font"]) if f["dl"] else ""))
table = "export const SKINS = [\n" + ",\n".join(rows) + "\n];\n"
io.open(os.path.join(HERE, "skins_table.js"), "w", encoding="utf-8", newline="\n").write(table)
print("skin table written, %d need a webfont" % sum(1 for s in SKINS if FONTS[s["font"]]["dl"]))
print("no download needed:", ", ".join(s["name"] for s in SKINS if not FONTS[s["font"]]["dl"]))
