export const SKINS = [
  { key: "warm-paper", layout: "cards", base: 22, group: "daylight" },
  { key: "sand", layout: "cards", base: 22, group: "daylight", face: "atkinson" },
  { key: "night", layout: "cards", base: 22, group: "night" },
  { key: "broadsheet", layout: "plain", base: 22, group: "daylight", face: "literata" },
  { key: "lamp", layout: "plain", base: 22, group: "night", face: "literata" },
  { key: "large-serif", layout: "plain", base: 26, group: "lowvision" },
  { key: "blue-accent", layout: "stripe", base: 22, group: "lowvision", face: "public" },
  { key: "amber-night", layout: "stripe", base: 22, group: "night", face: "atkinson" },
  { key: "forest", layout: "stripe", base: 22, group: "night", face: "nunito" },
  { key: "appointment-slip", layout: "ticket", base: 22, group: "daylight", face: "mono" },
  { key: "night-slip", layout: "ticket", base: 22, group: "night", face: "mono" },
  { key: "pale-gold", layout: "ticket", base: 22, group: "lowvision", face: "bitter" },
  { key: "day-plan", layout: "gutter", base: 22, group: "daylight", face: "lexend" },
  { key: "departures", layout: "gutter", base: 22, group: "night", face: "oswald" },
  { key: "strong-dark", layout: "gutter", base: 22, group: "lowvision" },
  { key: "terracotta", layout: "notice", base: 22, group: "daylight", face: "archivo" },
  { key: "block", layout: "notice", base: 22, group: "night", face: "archivo" },
  { key: "amber-on-black", layout: "notice", base: 22, group: "lowvision", face: "atkinson" },
  { key: "calm", layout: "one", base: 22, group: "daylight", face: "lexend" },
  { key: "plum", layout: "one", base: 22, group: "night", face: "lexend" },
  { key: "the-next-thing", layout: "one", base: 26, group: "lowvision", face: "lexend" },
  { key: "two-tiles", layout: "tiles", base: 22, group: "daylight", face: "archivo" },
  { key: "strong-light", layout: "tiles", base: 22, group: "lowvision", face: "atkinson" },
  { key: "quiet-stone", layout: "tiles", base: 22, group: "daylight", face: "public" }
];
